xcodebuild_arguments:
    - "-workspace"
    - "Aircall.xcworkspace"
    - "-scheme"
    - "Aircall"
swift_version: 5.0.1
min_acl: private
author: Yanis SID-AHMED GARCIA
author_url: https://github.com/aircall
github_url: https://github.com/aircall/ios-test
exclude:
  - "Pods/"
copyright: '© 2019 [Aircall](https://github.com/aircall) under [open source license](https://github.com/aircall/blob/master/LICENSE).'
theme: fullwidth

custom_categories:

  - name: Architecture
    children:
      - AppDelegate
      - AppCoordinator
      - Coordinator
      - ViewModel

  - name: Network
    children:
      - Aircall
      - AircallError
      - ObservableType

  - name: Payload
    children:
      - WSCalls
      - WSCall
      - WSReset
      - WSError
      - WSResponse
      - CallType
      - CallDirection

  - name: CoreData
    children:
      - CDCall
      - RxDataSources

  - name: Component
    children:
      - ACTitleLabel
      - ACSubtitleLabel
      - ACHeaderLabel
      - ACRefreshControl

  - name: Theme
    children:
      - Theme

  - name: Color
    children:
      - ColorKey
      - Color

  - name: Localization
    children:
      - LocalizedKey
      - LocalizedString

  - name: CallList
    children:
      - CallListModel
      - CallListViewController
      - CallListTableViewCell
      - CallListViewModel
      - CallListCoordinator
      - ShowCallDetails

  - name: CallDetails
    children:
      - CallDetailsModel
      - CallDetailsViewController
      - CallDetailsTableViewCell
      - CallDetailsViewModel
      - CallDetailsCoordinator

  - name: Utils
    children:
      - ACDate
      - Banner
      - Configurator

  - name: Protocol
    children:
      - CallDisplayable
      - CallRepresentable
      - CoreDataStorable
      - Sortable

  - name: Extension
    children:
      - UIActivityIndicatorView
      - UIRefreshControl

  - name: YSKit
    children:
      - YSLabel
      - YSRefreshControl
