# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Aircall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aircall

  # Lint
  pod 'SwiftLint'

  # Network
	pod 'Moya/RxSwift'

	# RxSwift
	pod 'RxSwiftExt'
  pod 'RxCocoa'

  # Data
	pod 'RxCoreData'
  pod 'RxDataSources'

	# Utils
	pod 'Reusable'
	pod 'NotificationBannerSwift'

  # Errors

  target 'AircallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AircallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
